# Generated by Django 2.0.7 on 2018-08-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talib', '0004_dawra_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('dawra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talib.Dawra')),
            ],
        ),
    ]
